# -*- coding: utf-8 -*-
"""Car_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbZtc5-Sbz7pGoFs4g2yYClhWQAWYeR6
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

car=pd.read_csv('dataset.csv')





car.isnull().sum()


# prompt: drop the missing value

car.dropna(inplace=True)
car.isnull().sum()

# most of the values are missing for New_Price, drop New_Price Column

car.drop(['New_Price'],axis=1,inplace=True)

# drop raw with missing values

car.dropna(inplace=True)
car.isnull().sum()




# prompt: Unique values in Name and count

# Count unique values in the 'Name' column
name_counts = car['Name'].value_counts()
name_counts

# prompt: split Name variable

# Split the 'Name' column into multiple columns
car[['Manufacturer', 'Model']] = car['Name'].str.split(' ',n=1, expand=True)



car.drop(['Name'],axis=1,inplace=True)

# prompt: remove string valur in Mileage ,Power, Engine

# Remove string values in 'Mileage', 'Power', and 'Engine' columns

# Define a function to clean the columns
def clean_column(value):
    if isinstance(value, str):  # Check if the value is a string
        value = value.split(" ")[0]  # Split at space, take the first part
        try:
          return float(value) #Convert to float
        except ValueError:
          return np.nan # Handle cases where conversion fails
    return value


car['Mileage'] = car['Mileage'].apply(clean_column)
car['Power'] = car['Power'].apply(clean_column)
car['Engine'] = car['Engine'].apply(clean_column)


# prompt: rename column title Mileage to Mileage(Kmpl/Kmkg), Power to Power(CC), Engine to Engine(bhp) and give column name

# Rename columns
car = car.rename(columns={'Mileage': 'Mileage(Kmpl/Kmkg)', 'Power': 'Power(CC)', 'Engine': 'Engine(bhp)'})



car.drop(['Model'],axis=1,inplace=True)
car.drop(['Unnamed: 0'],axis=1,inplace=True)





# prompt: correlation metrix  for car value exclude location, fuel type, owner tyoe, transmission, Manufacturer

# Exclude specified columns for correlation matrix
cols_to_exclude = ['Location', 'Fuel_Type', 'Owner_Type', 'Transmission', 'Manufacturer']
cols_for_correlation = [col for col in car.columns if col not in cols_to_exclude]

# Calculate the correlation matrix
correlation_matrix = car[cols_for_correlation].corr()





# prompt: introduce new colun of age whivh show current age of car regarding current year-Year

import datetime

current_year = datetime.datetime.now().year

def calculate_age(year):
  return current_year - year

car['Age'] = car['Year'].apply(calculate_age)



# prompt: encode Fuel_Type, Transmission, Owner type,Manucturer

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Define the columns to encode
categorical_cols = ['Fuel_Type', 'Transmission', 'Owner_Type', 'Manufacturer']

# Iterate through the columns and apply Label Encoding
for col in categorical_cols:
    car[col] = le.fit_transform(car[col])





# prompt: for the linear regression model split the data into train and test with test size 0.3
# for x drop location, year, Price

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = car.drop(['Location', 'Year', 'Price'], axis=1)
y = car['Price']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)



# prompt: generate linear regrestion model train and test

from sklearn.linear_model import LinearRegression

# Initialize and train the linear regression model
lr = LinearRegression()
lr.fit(X_train,y_train)

# Make predictions on the test set
y_pred = lr.predict(X_test)

# Evaluate the model (example: R-squared)
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared: {r2}")

# prompt: detail about lr and statestic signicance table

import statsmodels.api as sm

# Add a constant to the independent variables
X_train_sm = sm.add_constant(X_train)

# Fit the OLS model
lr_sm = sm.OLS(y_train, X_train_sm).fit()

# Print the summary of the model
print(lr_sm.summary())

# prompt: dropwhich varible p value higher than 0.05 and retrain model

# Get p-values from the statsmodels summary
p_values = lr_sm.pvalues

# Identify variables with p-values > 0.05
variables_to_drop = p_values[p_values > 0.05].index.tolist()

# Remove the constant from the list of variables to drop
if 'const' in variables_to_drop:
    variables_to_drop.remove('const')

# Drop the insignificant variables from the feature set
X_train_new = X_train.drop(variables_to_drop, axis=1)
X_test_new = X_test.drop(variables_to_drop, axis=1)

# Retrain the model with the reduced feature set
lr_new = LinearRegression()
lr_new.fit(X_train_new, y_train)

# Make predictions on the test set
y_pred_new = lr_new.predict(X_test_new)

# Evaluate the new model
r2_new = r2_score(y_test, y_pred_new)
print(f"R-squared after removing insignificant variables: {r2_new}")

# Add a constant to the new independent variables and refit statsmodels
X_train_sm_new = sm.add_constant(X_train_new)
lr_sm_new = sm.OLS(y_train, X_train_sm_new).fit()
print(lr_sm_new.summary())

from sklearn.model_selection import cross_val_score
cross_val_score(lr,X_test,y_test,cv=5)

import pickle
filename='car_price_prediction.sav'
pickle.dump(lr,open(filename,'wb'))

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import datetime

# Set page configuration
st.set_page_config(page_title="Car Price Predictor", page_icon="🚗", layout="centered")

# Load model
try:
    model = pickle.load(open('car_price_prediction.sav', 'rb'))
except FileNotFoundError:
    st.error("Error: Model file 'car_price_prediction.sav' not found. Please ensure it is in the app directory.")
    st.stop()

# Dictionary for label encoding (MUST match training encoding)
fuel_type_map = {'Petrol': 1, 'Diesel': 0, 'CNG': 2, 'LPG': 3, 'Electric': 4}
transmission_map = {'Manual': 1, 'Automatic': 0}
owner_type_map = {'First': 0, 'Second': 1, 'Third': 2, 'Fourth & Above': 3}
manufacturer_map = {
    'Maruti': 0, 'Hyundai': 2, 'Honda': 1, 'Toyota': 3, 'Ford': 4, 
    'Mahindra': 5, 'Mitsubishi': 6, 'BMW': 7, 'Volkswagen': 8, 
    'Nissan': 9, 'Tata': 10, 'Audi': 11, 'Volvo': 12, 'Renault': 13, 'Fiat': 14
}

# Streamlit app
st.title("🚗 Car Price Predictor")
st.markdown("Enter the car details below to predict its price. All fields are required.")

# Create a form for user input
with st.form(key="car_form"):
    st.header("Car Details")

    # Numerical inputs
    kms = st.number_input("Kilometers Driven", min_value=0, value=50000, step=1000,
                          help="Enter the total kilometers the car has been driven.")
    mileage = st.number_input("Mileage (Km/L or Km/Kg)", min_value=0.0, value=18.5, step=0.1,
                             help="Enter the car's fuel efficiency (e.g., 18.5 Km/L).")
    engine = st.number_input("Engine Capacity (CC)", min_value=0.0, value=1197.0, step=1.0,
                             help="Enter the engine capacity in cubic centimeters (e.g., 1197).")
    power = st.number_input("Power (BHP)", min_value=0.0, value=82.0, step=0.1,
                            help="Enter the car's power in brake horsepower (e.g., 82).")
    seats = st.number_input("Number of Seats", min_value=1, max_value=20, value=5, step=1,
                            help="Enter the number of seats (e.g., 5).")

    # Year input
    current_year = datetime.datetime.now().year
    year = st.number_input("Year of Manufacture", min_value=1900, max_value=current_year, 
                           value=2018, step=1, help=f"Enter the car's manufacturing year (1900-{current_year}).")

    # Categorical inputs
    fuel = st.selectbox("Fuel Type", options=list(fuel_type_map.keys()),
                        help="Select the car's fuel type.")
    trans = st.selectbox("Transmission Type", options=list(transmission_map.keys()),
                         help="Select the car's transmission type.")
    owner = st.selectbox("Owner Type", options=list(owner_type_map.keys()),
                         help="Select the ownership history.")
    manu = st.selectbox("Manufacturer", options=list(manufacturer_map.keys()),
                        help="Select the car's manufacturer.")

    # Submit button
    submit_button = st.form_submit_button(label="Predict Price")

# Process form submission
if submit_button:
    # Compute age
    age = current_year - year

    # Encode categorical inputs
    fuel_encoded = fuel_type_map[fuel]
    trans_encoded = transmission_map[trans]
    owner_encoded = owner_type_map[owner]
    manu_encoded = manufacturer_map[manu]

    # Create input DataFrame
    user_input = pd.DataFrame([{
        'Kilometers_Driven': kms,
        'Mileage(Kmpl/Kmkg)': mileage,
        'Engine(bhp)': engine,
        'Power(CC)': power,
        'Seats': seats,
        'Fuel_Type': fuel_encoded,
        'Transmission': trans_encoded,
        'Owner_Type': owner_encoded,
        'Manufacturer': manu_encoded,
        'Age': age
    }])

    # Ensure columns match trained model
    try:
        user_input = user_input[model.feature_names_in_]
    except KeyError as e:
        st.error(f"Error: Model expects different features. Issue: {str(e)}")
        st.stop()

    # Predict
    try:
        predicted_price = model.predict(user_input)[0]
        predicted_price = predicted_price * 10000  # Assuming model outputs in lakhs
        st.success(f"✅ Predicted Car Price: ₹{predicted_price:,.2f}")
    except Exception as e:
        st.error(f"Error during prediction: {str(e)}")

# Add some footer info
st.markdown("---")
st.markdown("**Note**: The predicted price is in Indian Rupees (₹), assuming the model outputs in lakhs. Ensure all inputs are accurate for reliable predictions.")
st.markdown("Built with ❤️ using Streamlit | Model trained on car dataset")
