# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbZtc5-Sbz7pGoFs4g2yYClhWQAWYeR6
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

car=pd.read_csv('dataset.csv')

car

car.info()

car.isnull().sum()

# prompt: plot heat map for missing value in each varible

plt.figure(figsize=(10, 6))
sns.heatmap(car.isnull(),yticklabels=False,cbar=False,cmap='viridis')

# prompt: drop the missing value

car.dropna(inplace=True)
car.isnull().sum()

# most of the values are missing for New_Price, drop New_Price Column

car.drop(['New_Price'],axis=1,inplace=True)

# drop raw with missing values

car.dropna(inplace=True)
car.isnull().sum()
car.info()
car.shape

car.describe()

sns.pairplot(car)

# prompt: Unique values in Name and count

# Count unique values in the 'Name' column
name_counts = car['Name'].value_counts()
name_counts

# prompt: split Name variable

# Split the 'Name' column into multiple columns
car[['Manufacturer', 'Model']] = car['Name'].str.split(' ',n=1, expand=True)

# Display the updated DataFrame
car

car.drop(['Name'],axis=1,inplace=True)

# prompt: remove string valur in Mileage ,Power, Engine

# Remove string values in 'Mileage', 'Power', and 'Engine' columns

# Define a function to clean the columns
def clean_column(value):
    if isinstance(value, str):  # Check if the value is a string
        value = value.split(" ")[0]  # Split at space, take the first part
        try:
          return float(value) #Convert to float
        except ValueError:
          return np.nan # Handle cases where conversion fails
    return value


car['Mileage'] = car['Mileage'].apply(clean_column)
car['Power'] = car['Power'].apply(clean_column)
car['Engine'] = car['Engine'].apply(clean_column)

car

car.info()

# prompt: rename column title Mileage to Mileage(Kmpl/Kmkg), Power to Power(CC), Engine to Engine(bhp) and give column name

# Rename columns
car = car.rename(columns={'Mileage': 'Mileage(Kmpl/Kmkg)', 'Power': 'Power(CC)', 'Engine': 'Engine(bhp)'})

# Display column names
car.columns

car.drop(['Model'],axis=1,inplace=True)
car.drop(['Unnamed: 0'],axis=1,inplace=True)

car.columns

sns.pairplot(car)

# prompt: correlation metrix  for car value exclude location, fuel type, owner tyoe, transmission, Manufacturer

# Exclude specified columns for correlation matrix
cols_to_exclude = ['Location', 'Fuel_Type', 'Owner_Type', 'Transmission', 'Manufacturer']
cols_for_correlation = [col for col in car.columns if col not in cols_to_exclude]

# Calculate the correlation matrix
correlation_matrix = car[cols_for_correlation].corr()

# Display the correlation matrix
print(correlation_matrix)

# You can also visualize the correlation matrix using a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

# prompt: introduce new colun of age whivh show current age of car regarding current year-Year

import datetime

current_year = datetime.datetime.now().year

def calculate_age(year):
  return current_year - year

car['Age'] = car['Year'].apply(calculate_age)

# prompt: generate histogram for Manufacturer count

plt.figure(figsize=(10, 6))
sns.countplot(x='Manufacturer', data=car)
plt.title('Manufacturer Count')
plt.xlabel('Manufacturer')
plt.ylabel('Count')
plt.xticks(rotation=90)  # Rotate x-axis labels for better readability
plt.show()

# prompt: encode Fuel_Type, Transmission, Owner type,Manucturer

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Define the columns to encode
categorical_cols = ['Fuel_Type', 'Transmission', 'Owner_Type', 'Manufacturer']

# Iterate through the columns and apply Label Encoding
for col in categorical_cols:
    car[col] = le.fit_transform(car[col])

# Display the updated DataFrame
car

car



# prompt: for the linear regression model split the data into train and test with test size 0.3
# for x drop location, year, Price

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = car.drop(['Location', 'Year', 'Price'], axis=1)
y = car['Price']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)



# prompt: generate linear regrestion model train and test

from sklearn.linear_model import LinearRegression

# Initialize and train the linear regression model
lr = LinearRegression()
lr.fit(X_train,y_train)

# Make predictions on the test set
y_pred = lr.predict(X_test)

# Evaluate the model (example: R-squared)
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print(f"R-squared: {r2}")

# prompt: detail about lr and statestic signicance table

import statsmodels.api as sm

# Add a constant to the independent variables
X_train_sm = sm.add_constant(X_train)

# Fit the OLS model
lr_sm = sm.OLS(y_train, X_train_sm).fit()

# Print the summary of the model
print(lr_sm.summary())

# prompt: dropwhich varible p value higher than 0.05 and retrain model

# Get p-values from the statsmodels summary
p_values = lr_sm.pvalues

# Identify variables with p-values > 0.05
variables_to_drop = p_values[p_values > 0.05].index.tolist()

# Remove the constant from the list of variables to drop
if 'const' in variables_to_drop:
    variables_to_drop.remove('const')

# Drop the insignificant variables from the feature set
X_train_new = X_train.drop(variables_to_drop, axis=1)
X_test_new = X_test.drop(variables_to_drop, axis=1)

# Retrain the model with the reduced feature set
lr_new = LinearRegression()
lr_new.fit(X_train_new, y_train)

# Make predictions on the test set
y_pred_new = lr_new.predict(X_test_new)

# Evaluate the new model
r2_new = r2_score(y_test, y_pred_new)
print(f"R-squared after removing insignificant variables: {r2_new}")

# Add a constant to the new independent variables and refit statsmodels
X_train_sm_new = sm.add_constant(X_train_new)
lr_sm_new = sm.OLS(y_train, X_train_sm_new).fit()
print(lr_sm_new.summary())

from sklearn.model_selection import cross_val_score
cross_val_score(lr,X_test,y_test,cv=5)

import pickle
filename='car_price_prediction.sav'
pickle.dump(lr,open(filename,'wb'))



